apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: localhost:5000/frontend-image
      context: .
      docker:
        dockerfile: Dockerfile
      tagPolicy:
        gitCommit: true  
deploy:
  kubectl:
    manifests:
      - ../K8s/frontend-app.yaml
push:
  artifacts:
    - image: localhost:5000/frontend-image
      pusher:
        local: true  
