apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: exam
  name: list-users-role-binding
subjects:
- kind: ServiceAccount
  name: list-users-sa
  namespace: exam
roleRef:
  kind: Role
  name: list-users-role
  apiGroup: rbac.authorization.k8s.io
